-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.movie
(
    id bigint NOT NULL,
    original_title character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.imdb_details
(
    id bigint NOT NULL,
    imdb_id bigint NOT NULL,
    popularity double precision,
    vote_count bigint,
    vote_average double precision,
    PRIMARY KEY (imdb_id)
);

CREATE TABLE IF NOT EXISTS public.movie_genre
(
    id bigint NOT NULL,
    genre character varying NOT NULL,
    PRIMARY KEY (id, genre)
);

CREATE TABLE IF NOT EXISTS public.release_details
(
    id bigint NOT NULL,
    release_date date,
    release_year integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.finances
(
    id bigint NOT NULL,
    budget bigint,
    revenue bigint,
    budget_adj real,
    revenue_adj real,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.metadata
(
    id bigint NOT NULL,
    keywords character varying[],
    tagline text,
    runtime bigint,
    homepage text,
    overview text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.directed
(
    id bigint NOT NULL,
    director_name character varying,
    PRIMARY KEY (id, director_name)
);

CREATE TABLE IF NOT EXISTS public."cast"
(
    id bigint NOT NULL,
    actor_name character varying NOT NULL,
    PRIMARY KEY (id, actor_name)
);

CREATE TABLE IF NOT EXISTS public.production
(
    id bigint NOT NULL,
    production_company character varying,
    PRIMARY KEY (id, production_company)
);

ALTER TABLE IF EXISTS public.imdb_details
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.movie_genre
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.release_details
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.finances
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.metadata
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.directed
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."cast"
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.production
    ADD FOREIGN KEY (id)
    REFERENCES public.movie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;